server {
    listen 80;
    server_name code.zestrade.com;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name code.zestrade.com;

    ssl_certificate     ./certs/code.zestrade.com/code.zestrade.com.crt;
    ssl_certificate_key ./certs/code.zestrade.com/code.zestrade.com.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://127.0.0.1:18089;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }
}

